version: "3.2"

services:
  api:
    container_name: api
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - type: "bind"
        source: "./"
        target: "/go/src/rocket-server/server/api"
    ports:
      - 8082:8082
