version: "3.7"

services:  
  events:
    container_name: events
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - type: "bind"
        source: "./"
        target: "/go/src/rocket-server/server/events"
    ports:
      - 8082:8082