version: "3.2"

services:
  redisdb:
    container_name: redisdb
    build:
      context: ./pkg/db
      dockerfile: Dockerfile
    ports:
      - 6379:6379  
  
  events:
    container_name: events
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    depends_on:
      - redisdb