# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    machine: true # Use a Linux VM instead of docker environment
    working_directory: ~/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout # check out source code to working directory
      - run:
          name: Events service - build
          command: docker-compose --file ./server/events/docker-compose.yml build
      - run:
          name: Events service - test
          command: go test -v rocket-server/server/events/...
